### ISSUE TITLE
About transform.py

### ISSUE THREAD

**Issue by YoloEliwa** [XueJiang16/ssl-torch#1]
Thanks for applying your code ! And I have some question about transform.py. In your paper, I found the datasets you used have two channels, but when I see you code of **contrast.py line 55,** it seems **x [nums , samples]**，rather than **x [nums , channels, samples]**. So, you only use one channel？ and whether **transform.py** can only be used for single channel signals？
Thanks you very much, I am looking forward to receiving your reply

**Comment by XueJiang16** [comment]
I only used single-channel EEG signals as other papers did but I have not tried multi-channel signals. I think it may work and you can have a try.
